const filterButtonData = {
  cardType: [
    {
      id: "normal monster",
      name: "type",
      value: "type",
      label: "Normal Monster",
    },
    {
      id: "effect monster",
      name: "type",
      value: "type",
      label: "Effect Monster",
    },
    {
      id: "ritual monster",
      name: "type",
      value: "type",
      label: "Ritual Monster",
    },
    {
      id: "fusion monster",
      name: "type",
      value: "type",
      label: "Fusion Monster",
    },
    {
      id: "synchro monster",
      name: "type",
      value: "type",
      label: "Synchro Monster",
    },
    {
      id: "xyz monster",
      name: "type",
      value: "type",
      label: "XYZ Monster",
    },
    {
      id: "pendulum monster",
      name: "type",
      value: "type",
      label: "Pendulum Monster",
    },
    {
      id: "link monster",
      name: "type",
      value: "type",
      label: "Link Monster",
    },
    {
      id: "token monster",
      name: "type",
      value: "type",
      label: "Token Monster",
    },
    {
      id: "spell",
      name: "type",
      value: "type",
      label: "Spell",
    },
    {
      id: "trap",
      name: "type",
      value: "type",
      label: "Trap",
    },
  ],

  cardRace: [
    {
      id: "aqua",
      name: "monster-race",
      value: "race",
      label: "Aqua",
    },
    {
      id: "beast",
      name: "monster-race",
      value: "race",
      label: "Beast",
    },
    {
      id: "beast-warrior",
      name: "monster-race",
      value: "race",
      label: "Beast Warrior",
    },
    {
      id: "cyberse",
      name: "monster-race",
      value: "race",
      label: "Cyberse",
    },
    {
      id: "dinosaur",
      name: "monster-race",
      value: "race",
      label: "Dinosaur",
    },
    {
      id: "divine-beast",
      name: "monster-race",
      value: "race",
      label: "Divine Beast",
    },
    {
      id: "dragon",
      name: "monster-race",
      value: "race",
      label: "Dragon",
    },
    {
      id: "fairy",
      name: "monster-race",
      value: "race",
      label: "Fairy",
    },
    {
      id: "fiend",
      name: "monster-race",
      value: "race",
      label: "Fiend",
    },
    {
      id: "fish",
      name: "monster-race",
      value: "race",
      label: "Fish",
    },
    {
      id: "insect",
      name: "monster-race",
      value: "race",
      label: "Insect",
    },
    {
      id: "machine",
      name: "monster-race",
      value: "race",
      label: "Machine",
    },
    {
      id: "plant",
      name: "monster-race",
      value: "race",
      label: "Plant",
    },
    {
      id: "psychic",
      name: "monster-race",
      value: "race",
      label: "Psychic",
    },
    {
      id: "pyro",
      name: "monster-race",
      value: "race",
      label: "Pyro",
    },
    {
      id: "reptile",
      name: "monster-race",
      value: "race",
      label: "Reptile",
    },
    {
      id: "rock",
      name: "monster-race",
      value: "race",
      label: "Rock",
    },
    {
      id: "sea-serpent",
      name: "monster-race",
      value: "race",
      label: "Sea Serpent",
    },
    {
      id: "spellcaster",
      name: "monster-race",
      value: "race",
      label: "Spellcaster",
    },
    {
      id: "thunder",
      name: "monster-race",
      value: "race",
      label: "Thunder",
    },
    {
      id: "warrior",
      name: "monster-race",
      value: "race",
      label: "Warrior",
    },
    {
      id: "winged-beast",
      name: "monster-race",
      value: "race",
      label: "Winged Beast",
    },
    {
      id: "wyrm",
      name: "monster-race",
      value: "race",
      label: "Wyrm",
    },
    {
      id: "zombie",
      name: "monster-race",
      value: "race",
      label: "Zombie",
    },
  ],

  cardLevel: [
    {
      id: "1",
      name: "monster-level",
      value: "level",
      label: "1",
    },
    {
      id: "2",
      name: "monster-level",
      value: "level",
      label: "2",
    },
    {
      id: "3",
      name: "monster-level",
      value: "level",
      label: "3",
    },
    {
      id: "4",
      name: "monster-level",
      value: "level",
      label: "4",
    },
    {
      id: "5",
      name: "monster-level",
      value: "level",
      label: "5",
    },
    {
      id: "6",
      name: "monster-level",
      value: "level",
      label: "6",
    },
    {
      id: "7",
      name: "monster-level",
      value: "level",
      label: "7",
    },
    {
      id: "8",
      name: "monster-level",
      value: "level",
      label: "8",
    },
    {
      id: "9",
      name: "monster-level",
      value: "level",
      label: "9",
    },
    {
      id: "10",
      name: "monster-level",
      value: "level",
      label: "10",
    },
    {
      id: "11",
      name: "monster-level",
      value: "level",
      label: "11",
    },
    {
      id: "12",
      name: "monster-level",
      value: "level",
      label: "12",
    },
  ],

  cardLinkVal: [
    {
      id: "1",
      name: "monster-linkval",
      value: "linkval",
      label: "1",
    },
    {
      id: "2",
      name: "monster-linkval",
      value: "linkval",
      label: "2",
    },
    {
      id: "3",
      name: "monster-linkval",
      value: "linkval",
      label: "3",
    },
    {
      id: "4",
      name: "monster-linkval",
      value: "linkval",
      label: "4",
    },
    {
      id: "5",
      name: "monster-linkval",
      value: "linkval",
      label: "5",
    },
    {
      id: "6",
      name: "monster-linkval",
      value: "linkval",
      label: "6",
    },
  ],

  cardAttribute: [
    {
      id: "dark",
      name: "monster-attribute",
      value: "attribute",
      label: "Dark",
    },
    {
      id: "light",
      name: "monster-attribute",
      value: "attribute",
      label: "Light",
    },
    {
      id: "fire",
      name: "monster-attribute",
      value: "attribute",
      label: "Fire",
    },
    {
      id: "water",
      name: "monster-attribute",
      value: "attribute",
      label: "Water",
    },
    {
      id: "earth",
      name: "monster-attribute",
      value: "attribute",
      label: "Earth",
    },
    {
      id: "wind",
      name: "monster-attribute",
      value: "attribute",
      label: "Wind",
    },
    {
      id: "divine",
      name: "monster-attribute",
      value: "attribute",
      label: "Divine",
    },
  ],

  cardSpellRace: [
    {
      id: "normal",
      name: "spell-race",
      value: "race",
      label: "Normal",
    },
    {
      id: "quick-play",
      name: "spell-race",
      value: "race",
      label: "Quick-play",
    },
    {
      id: "continuous",
      name: "spell-race",
      value: "race",
      label: "Continuous",
    },
    {
      id: "field",
      name: "spell-race",
      value: "race",
      label: "Field",
    },
    {
      id: "equip",
      name: "spell-race",
      value: "race",
      label: "Equip",
    },
    {
      id: "ritual",
      name: "spell-race",
      value: "race",
      label: "Ritual",
    },
  ],

  cardTrapRace: [
    {
      id: "normal",
      name: "trap-race",
      value: "race",
      label: "Normal",
    },
    {
      id: "continuous",
      name: "trap-race",
      value: "race",
      label: "Continuous",
    },
    {
      id: "counter",
      name: "trap-race",
      value: "race",
      label: "Counter",
    },
  ],
};

export default filterButtonData;
